#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1421253951                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Now                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : A minimal calendar

enable_smart_app_banner                   : false                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Brandon Asuncion                                
your_link                                 : https://brandonasuncion.dev/                     
your_city                                 : Los Angeles                                
email_address                             : me@brandonasuncion.dev
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : brandonasuncion
youtube_username                          :


copyright                                 : © 2020 Brandon Asuncion
copyright_text_color                      : "#86868b"


# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Keep on top of things
    description                           : See your daily events and reminders and coordinate across multiple days at a time.
    fontawesome_icon_name                 : calendar-alt

  - title                                 : Focus on your tasks
    description                           : Card views give detailed information on your events and reminders.
    fontawesome_icon_name                 : check

  - title                                 : iCloud Sync
    description                           : Sync your calendars to organize your schedule from multiple devices.
    fontawesome_icon_name                 : cloud

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.0
topbar_title_color                        : "#000000"

cover_image                               :                     # Replace with alternative image path or image URL.
cover_overlay_color                       : "#ffffff"
cover_overlay_transparency                : 0.0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#006fc9"

app_title_color                           : "#000000"
app_price_color                           : "#202020"
app_description_color                     : "#181818"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#ffffff"
feature_icons_background_color            : "#202020"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#86868b"












####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown